version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - echo ***************************** DOCKER BUILDX local *****************************
      # - docker buildx build -t $IMAGE_REPO_NAME:$IMAGE_TAG . --platform linux/arm64
      # - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      # - docker images
      # - docker image inspect $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker build -t udacity-p03 .
      # - docker buildx build -t udacity-p03-ecr-repo . --platform linux/arm64
      - docker image inspect udacity-p03:latest | grep "Architecture"
      - docker tag udacity-p03:latest 058700463501.dkr.ecr.us-east-1.amazonaws.com/udacity-p03:latest
      - docker push 058700463501.dkr.ecr.us-east-1.amazonaws.com/udacity-p03:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG