# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.10-slim as base

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install curl using the package manager (apt-get for Debian-based images)
# RUN apt-get update && apt-get install -y curl

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
# RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app

# Install pip requirements
COPY requirements.txt .
RUN python -m pip install -r requirements.txt

# USER appuser

COPY . .

EXPOSE 5000

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
# CMD ["gunicorn", "--bind", "0.0.0.0:5000", "repo.project3/cd12355-microservices-aws-kubernetes-project-starter/analytics/app:app"]
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "config:app"]

# gunicorn 'app:app' --bind 0.0.0.0:5000
