apiVersion: v1
kind: Service
metadata:
  name: admin-api
spec:
  selector:
    app.kubernetes.io/name: admin-api
  type: LoadBalancer
  ports:
  - name: "5000"
    protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: admin-api
  labels:
    name: admin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: admin-api
  template:
    metadata:
      labels:
        service: admin-api
    spec:
      containers:
      - name: admin-api
        image: 058700463501.dkr.ecr.us-east-1.amazonaws.com/udacity-p03
        imagePullPolicy: Always
        # livenessProbe:
        #   httpGet:
        #     path: /health_check
        #     port: 5000
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        # readinessProbe:
        #   httpGet:
        #     path: "/readiness_check"
        #     port: 5000
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 5
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          value: app-db
      restartPolicy: Always
